### ISSUE TITLE
Question: How do you get the iOS version?

### ISSUE THREAD

**Issue by jtrees** [stijnvdb88/Snap.Net#16]
The readme mentions an iOS version but it's unclear to me how to get hold of it. Is there documentation somewhere?

**Comment by stijnvdb88** [comment]
Hi! I never actually published it: releasing an app on the App Store requires a developer account, which Apple charges 99$/year for. I was looking into it at one point but honestly just forgot about it, and you're the first person to ask since then :) I'll go ahead and set this up anyway, maybe just make it a paid app to try to recover part of the expense.

**Comment by jtrees** [comment]
Saweeet! I look forward to finding it there.

**Comment by stijnvdb88** [comment]
It just went live! :) 
https://apps.apple.com/us/app/snapcast-control/id1552559653#?platform=iphone

**Comment by jtrees** [comment]
Awesome! Thanks again. I'll check it out tomorrow.

**Comment by stijnvdb88** [comment]
@jtrees quick update on this! I released an update a few minutes ago which introduces support for also playing audio on iOS - this is very much an experimental feature but I felt I could get away with it given the tiny userbase :D It should stay in sync without too many audible corrections, and should keep playing when backgrounded. Depending on the device you have you might need to tweak the client's latency - the only physical device I had available for testing here had a latency of ~30ms.

Please take a look and open new issues for any bugs you find :)

Thanks!

**Comment by jtrees** [comment]
@stijnvdb88 That sounds amazing!

The app works well as a remote. I haven't been able to figure out how to receive audio yet though. Is there something specific I should be doing to unlock the feature?

**Comment by stijnvdb88** [comment]
Thanks! that lock issue is worrying, I hope this is isn't the app process getting a lower priority during "sleep". I'd hoped setting the audio session category would have taken care of backgrounding/sleep priorities:

`session.SetCategory(AVAudioSessionCategory.Playback, AVAudioSessionCategoryOptions.MixWithOthers);` ([AppDelegate:44](https://github.com/stijnvdb88/Snap.Net/blob/player/Mobile/Mobile.iOS/AppDelegate.cs#L37))

I'm guessing playing music during sleep works just fine with other streaming apps (eg Spotify / internet radios etc) ? There must be some kind of priority flag somewhere that I missed :)

**Comment by jtrees** [comment]
> I'm guessing playing music during sleep works just fine with other streaming apps (eg Spotify / internet radios etc) ?

Yeah, Spotify playback works fine with the screen off.

**Comment by stijnvdb88** [comment]
Created a new issue for this: https://github.com/stijnvdb88/Snap.Net/issues/21 :)

**Comment by stijnvdb88** [comment]
@jtrees  Sorry, took a bit longer than usual to get the update through AppStore review :) It just went live a minute ago - please confirm in the other issue if it works for you now! (asking here because you wouldn't receive a notification otherwise)

The new version is 1.2 - might take a few hours for the update to become available on your phone.

Have a great weekend!
