### ISSUE TITLE
No audio from IPad/ IPhone

### ISSUE THREAD

**Issue by Prematurelee** [stijnvdb88/Snap.Net#24]
Hi Stijn,

I was so pleased to find this app. However for some reason I am not getting audio out from either IPad or IPhone. My Snapcast server is a basic install and there was no defined codec, so I modified the config to use FLAC just to make sure. I am not sure what I haven't got right!! Everthing else appears to be working, listing devices, adjusting volume etc. I also have a pi running as a client which is playing audio without any issue. Any pointers would be so gratefully received. Happy to pay the 0.99c ;o)

Thanks for your efforts in creating this app.

**Comment by stijnvdb88** [comment]
Hi there! It sounds like you're doing everything right - FLAC is the default codec anyway (eg. snapserver will use that one if nothing is explicitly set in the config), so that should be fine both with and without that modification :)

Does your iPhone or iPad show up in the client list once you tap the play button in the top right corner, or not even that? Also, does the button's icon change to a stop icon after tapping it, or does it just not respond at all? Could you perhaps record a short screen capture from one of your devices?

Thanks!

**Comment by Prematurelee** [comment]
Thanks for very quick reply.

iPad and iPhone both appear in the devices list both. Both respond to the play button being pressed, and correctly changes to stop. Volume is adjustable. All appears to be functioning, just no sound.

**Comment by stijnvdb88** [comment]
Ok, thanks :) Can you also tell me the specs for both devices? (model name + iOS version). Also, does it work if you try to play music using snapweb from either device? That's also enabled by default on the server, reachable via browser at http://<snapserver-ip>:1780

**Comment by Prematurelee** [comment]
Thanks once again for your prompt and helpful support. I had a look at what you suggested and I ended up just blowing away my Mopidy/ Snapserver install and rebuilt again from scratch. Happy to report it is all working now. VERY HAPPY!

Thanks again for creating an awesome app!

**Comment by stijnvdb88** [comment]
Thanks for the update, that's great to hear!
