### ISSUE TITLE
19.0.2 Out of Sync waking up from Sleep

### ISSUE THREAD

**Issue by almostserious** [stijnvdb88/Snap.Net#3]
Hi, I sometimes have a different latency if the program is running for a long time. Only way to fix, seems to be a restart of the application. 
I'm not 100% sure how to reproduce. Might be connected with the PC going to sleep and waking up.

*EDIT* Yes so turns out that after PC going to sleep and waking up this happens every time.
The sound is suddenly a little bit out of sync with the rest of the speakers.

**Comment by stijnvdb88** [comment]
Hi! thanks for narrowing it down :) I'll take a better look after work, but could you try and see if this also happens when using snapclient.exe directly?
You can test that by quitting Snap.Net, and then running

```C:\Program Files\Snap.Net\SnapClient\snapclient.exe -h <snapserver_ip>```

**Comment by almostserious** [comment]
I have been playing around a little bit with different settings. Yesterday i seemed to loose sync almost every 10minutes. When i switched from "no resample" to "resample to 48000:16" it was fine. Even though my audio card is set to 44100:16 it did not work when i set resample to that format though...  This also seems to work when waking up from sleep.

However, now doing the same test, without resample... its in sync for more than an hour already...

**Comment by almostserious** [comment]
scratch that.. today i have out of sync again even with resample. When I am trying to run snapclient.exe directly, upon waking up from sleep, it does not continue playing. I will keep it open for some hours to see if it goes out of sync.

**Comment by stijnvdb88** [comment]
ok, thanks! just out of curiosity, are you noticing increased cpu load or memory usage when it starts lagging behind? snapclient compensates when it gets too far out of sync so it shouldn't really matter...the only other thing I can think of is the clock itself being slightly off, but that wouldn't be fixed by restarting the application. 

I'll be adding some options for debugging in the next release  so we can also keep an eye on the DAC latency evolves :) you can do this yourself by looking at snapclient.exe's output in command prompt (it's the 6th number in each line that gets printed out every second or so), but that's pretty pointless if you can't reproduce the issue there.

A few more things we can test: are you able to reproduce it in exclusive mode? do you have any other sound devices this happens on (e.g. hdmi audio from your monitor) ?

**Comment by almostserious** [comment]
Yes, so i just tried it with Exclusive Mode. While i had to reduce the latency by another -50ms to be back in sync with the other speakers, with this option turned on it seems like I do not get anymore the out of sync stream over time. 

However, when waking up from sleep I get a long static noise. 
And of course, because its exclusive i cannot at the same time listen to another sound source.

**Comment by almostserious** [comment]
FYI.. after installing new versions this doesnt happen anymore. Works fine now. Im closing this issue

**Comment by stijnvdb88** [comment]
Thanks for the update!
