### ISSUE TITLE
Ability to control which audio devices show up in player interface

### ISSUE THREAD

**Issue by djmattyg007** [stijnvdb88/Snap.Net#34]
I have 11 audio devices and the list is only growing. It's a bit of a pain to have to manually locate the device I want to use for playback every time I open the player. Ideally, there would only be one device in the list - the one I configure.

Even better would be a way to say "this is the device to use" and then the player window just has a single big play/pause button so it's even easier to manage. This could then also be an option in the right-click menu of the system tray icon, making it as fast as possible to turn the playback on and off as desired.

**Comment by stijnvdb88** [comment]
Hi! Maybe I'm missing something, but if you always want the same device to be used, why not check the "auto-play" box for that device and leave it "playing" constantly? You could then toggle it on/off using the regular snapcast volume/mute controls. The player window isn't typically used all that often - it's mostly meant for the initial device configuration. Does the fact that your audio device list changes so often somehow cause these settings to reset?

I wouldn't go culling devices from that list, because part of the reason Snap.Net exists is to support multiple audio devices playing simultaneously from a single machine. In my case I've got 5 audio devices in that list, but do have 4 of them on auto-play. In cases like that, you do want new devices to appear on the list as soon as they're added.
