### ISSUE TITLE
How did you get metadata from mopidy working?

### ISSUE THREAD

**Issue by lucianm** [stijnvdb88/Snap.Net#48]
Thanks for this great piece of software, I'm using it since the early days!

I just updated few days ago my server and all clients to 0.27 and only then I found out there is a new meta_mopidy.py control script shipped with snapserver. Can you please tell me what needs to be configured to make that work (I didn't find a full, working configuration anywhere, but have seen your newest screenshot displays the metadata of mopidy with some cover art)?
I'm only seeing mopidy's metadata in Snap.NET if I'm using the old meta_mpd.py, with the new script nothing is shown. I'm running snapserver and 2 mopidy instances on my NAS, so my configuration is like this in /etc/snapserver.conf:
working:
`source = pipe:///tmp/snapfifo_mopidy_1?name=Mopidy_1&controlscript=meta_mpd.py&controlscriptparams=--mpd-port=6601%20--stream=Mopidy_1`
not working:
`source = pipe:///tmp/snapfifo_mopidy_1?name=Mopidy_1&controlscript=meta_mopidy.py&controlscriptparams=--mopidy-port=6681%20--stream=Mopidy_1`

My Mopidy_1 instance runs on ports 6681 and its MPD extension on port 6601, the Iris extension also has Snapcast enabled in the config, but I cannot see it in the web view, and also, the sanpcast configuration for the Iris extension contains:
```
[iris]
snapcast_stream = Mopidy_1

```
What is missing here, how can it be debugged?

**Comment by stijnvdb88** [comment]
Hi! I haven't tried the meta_mopidy.py plugin actually, those screenshots were made using the meta_mpd.py control plugin. Either should work with Snap.Net though - as long as either artUrl or svg metadata is sent by snapserver in the stream properties messages, Snap.Net will display it. If you're not seeing an image displayed in Snap.Net it probably means no artUrl/svg metadata was sent from snapserver, so probably a configuration issue. You can debug this by running snapserver with "--logging.filter debug". If you inspect the output, each time you change the track it should output some logs that include all the metadata it sends to clients connected to the control interface, eg. like this:

```
Mar 12 16:10:09 office snapserver[9478]: setProperties, stream: Stijn, properties: {"canControl":true,"canGoNext":true,"canGoPrevious":true,"canPause":true,"canPlay":true,"canSeek":false,"loopStatus":"none","metadata":{"album":"Little Animals","albumArtist":["Beasts Of Bourbon"],"artUrl":"http://coverartarchive.org/release/af9449c8-3727-4e24-8ff6-ed8161f4849f/19486188545-250.jpg","artist":["Beasts Of Bourbon"],"contentCreated":"2007","genre":["Rock"],"title":"I Don't Care About Nothing Anymore","trackId":"104","trackNumber":1,"url":"local:track:Beasts%20Of%20Bourbon/2007%20-%20Little%20Animals/01%20-%20I%20Don%27t%20Care%20About%20Nothing%20Anymore.mp3"},"playbackStatus":"paused","position":2.3239998817443848,"shuffle":false,"volume":42}
```
As you can see, this one has an artUrl field, which means Snap.Net can follow that link to display the image like you saw in the screenshot.

If you are seeing artUrl/svg metadata included here in your own logs but no image displayed in the UI, please let me know here, because that would mean it is a bug on the Snap.Net side :) if it's not included, try using the meta_mpd.py plugin - that one works fine for me. meta_mpd.py itself gets the artUrl by searching the musicbrainz database, and it does that by passing in the artist and album name for the query. That means if "album", "artist", and "albumArtist" are also missing/incorrect in the above metadata, it will never be able to look up the artUrl to begin with. Hope this helps!

**Comment by lucianm** [comment]
Thank you, that helped, and actually, I was able to see also some artwork when playing something from my local MP3 collection in Mopidy. It was the TuneIn extension which failed to provide meta_mpd.py with some information for artwork. And the new meta_mopidy.py does not work at all, not logging anything when the stream changes. So then Snap.NET seems to be working as expected, I'll close this issue then.
