### ISSUE TITLE
Error message waking up - Auto remove possible?

### ISSUE THREAD

**Issue by almostserious** [stijnvdb88/Snap.Net#6]
When the PC wakes up from sleep (with snap.net running)
The first connection always fails and i get the following error message:
![image](https://user-images.githubusercontent.com/14896478/86479916-4f5f5280-bd4d-11ea-8662-19d07aeb4437.png)

Usually it connects with the following tries. However, the error message remains.

Would it be possible to either:
1.Not show the error message if a successful connection was achieved with the following tries?
2.Remove the message after some time automatically?

Its set to auto restart on error with 3 attempts.

**Comment by stijnvdb88** [comment]
Thanks! Great suggestions both - will be included in the next release :)

**Comment by PD75** [comment]
This could also be a workaround for my problem: [https://github.com/badaix/snapcast/issues/657](url)

In Windows, I use HDMI for sound. Whenever Kodi starts, or I switch to console or TV, SnapClient crashes. And then I have to either reboot the computer or find my keyboard. This also some times happens when I switch to music mode (only Amp, no TV).

Basically the Audio Output disappears for a short time. 

Maybe a retry more infrequently when it has been off for a longer period of time. Like every 30 sec, or check for the audio source first.

**Comment by stijnvdb88** [comment]
@PD75 what's the error message Snap.Net shows in your case? Do you ever get the one below, or just a "device invalidated" wasapi error?

![image](https://user-images.githubusercontent.com/4498834/86532026-74bf9e00-bebe-11ea-94df-969e0df26031.png)

**Comment by PD75** [comment]
@stijnvdb88 I get the message you have. 
![Annotation 2020-06-30 203232](https://user-images.githubusercontent.com/10294795/86538432-537aa400-bef6-11ea-9c90-d940e4c7015f.png)

Also it wants to remove the device from Autoplay.
![Annotation 2020-06-30 203135](https://user-images.githubusercontent.com/10294795/86538421-465db500-bef6-11ea-9bc4-978d8506c3b0.png)

**Comment by stijnvdb88** [comment]
@PD75 thanks - that means your issue is a bit different, it won't be solved by changing how the error messages show up.

The current flow is:
1. detect audio device
2. attempt to start snapclient for device
3. if process crashes, show error and repeat flow

The catch here is that it only retries if the second step failed. If the first step fails, we show the "would you like to remove this device from auto-start" dialog and bail. In other words, the moment a device was no longer detected, the retry loop is stopped entirely. That's less than ideal for hdmi devices which are apt to disappear every once in a while :) I'll add an extra setting to optionally make it look for the device every x seconds like you suggested, along with flags for suppressing those error messages.

**Comment by PD75** [comment]
Thanks!

**Comment by stijnvdb88** [comment]
Hi! I just added a pre-release which hopefully solves these issues for both of you :)
https://github.com/stijnvdb88/Snap.Net/releases/tag/v0.20.01

You now have more control over how notifications work, and what happens when a devices goes missing:
![image](https://user-images.githubusercontent.com/4498834/89124604-38d52400-d4d0-11ea-9157-45a5ba474fd9.png)

Combined with the existing "Auto-restart on error" check, this should make Snap.Net a lot more robust. Whenever anything goes wrong it'll auto-recover as soon as it's able to, without requiring action from the user.
![image](https://user-images.githubusercontent.com/4498834/89124631-628e4b00-d4d0-11ea-8763-d28e08c4a8e5.png)

Please take a look and let me know!

**Comment by almostserious** [comment]
Thanks, waking up the PC now will first play the sound, then the error pops up, is removed automatically and after that it will reconnect and the music resumes :) Very nice.

**Comment by PD75** [comment]
@stijnvdb88 seems to work like a dream, I have not had to go into the gui of the computer since I installed it. I have watched netflix on my xbox over lunch then switch back to the computer sound only and it works.

Thanks!!!

**Comment by stijnvdb88** [comment]
Great to hear! Thanks again to both of you for reporting these issues!
